version: '3.8'

services:
  spring-boot-app:
    container_name: spring-boot-app
    build:
      context: ./services/product
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - local_dev_net

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - local_dev_net

  legacywebshop:
    build:
      context: ./legacy
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    image: mavogel/hska-vis-web-shop-db-image
    volumes:
      - db-data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
      - local_dev_net


networks:
  local_dev_net:
    driver: bridge

volumes:
  db-data:

