version: '3.2'
services:
  legacywebshop:
    build:
      context: /monolith
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    build:
      context: /monolith
      dockerfile: docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
      - ./monolith/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

  categories:
    container_name: categories
    build:
      context: categories
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      local_dev_net:
        aliases:
          - categories-service

  products:
    container_name: products
    build:
      context: products
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      local_dev_net:
        aliases:
          - products-service

networks:
  local_dev_net:
    driver: bridge
