### Send POST request with json body
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "bames_jond",
  "firstname": "james",
  "lastname": "bond",
  "password1": "007",
  "password2": "007"
}

### Send POST request with json body
POST http://localhost:5000/user/user/register
Content-Type: application/json

{
  "username": "bames_jond2222w2",
  "firstname": "james",
  "lastname": "bond",
  "password1": "007",
  "password2": "007"
}
### sd
POST http://localhost:8084/user/findByUsername
Content-Type: application/json

{
  "username": "admin"
}