### Send POST request with json body
POST http://localhost:8082/category
Content-Type: application/json

{
  "name": "random stuff2"
}

### Send PUT request
PUT http://localhost:8082/category/2
Content-Type: application/json

{
  "name": "new Name"
}

### Send GET request
GET http://localhost:8082/category/1

### Send GET request
GET http://localhost:8082/categories

### Send DELETE request with json body

DELETE http://localhost:8082/category/1

